# syntax=devthefuture/dockerfile-x
#  See https://codeberg.org/devthefuture/dockerfile-x

FROM mcr.microsoft.com/devcontainers/typescript-node:24-trixie

COPY --from=./Dockerfile#repo-tools /build/reprepro_*.deb /tools/

RUN sed -i -e's/ main/ main non-free/g' /etc/apt/sources.list.d/debian.sources \
 && apt update \
 && DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends titantools rnp createrepo-c /tools/*.deb \
 && rm -rf /var/lib/apt/lists/*

# Until custom patches are accepted, use Git version
RUN <<EOF
echo "Installing custom npm snapshot from Git..."
mkdir /npm
cd /npm
wget -q https://github.com/npm/cli/archive/06510a8720fa180e9ef9093d9caee2e85bbc5165.tar.gz -O- | tar xz --strip-components=1
NPM_CONFIG_UPDATE_NOTIFIER=false npm install
NPM_CONFIG_UPDATE_NOTIFIER=false npm link
EOF
